### ISSUE TITLE
elm-pages issues tracker

### ISSUE THREAD

**Issue by icidasset** [fission-suite/landing-page#2]
- [x] "Missing content" flash on page load
- [x] Generated static HTML sometimes is incorrect
- [ ] Can't start dir and file names with numbers
- [x] ~~Where do I put static assets that are not images?~~ `static` dir in project root
